services:
  - type: web
    name: vizzy-chat
    runtime: python
    buildCommand: |-
      pip install -r backend/requirements.txt &&
      cd frontend &&
      npm install &&
      npm run build &&
      cd ..
    startCommand: bash start.sh
    envVars:
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: REPLICATE_API_KEY
        sync: false
      - key: RUNWARE_API_KEY
        sync: false
      - key: AIML_API_KEY
        sync: false
